# Generated by Django 4.2.7 on 2023-11-23 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languge', models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('C#', 'C#'), ('Go', 'Go'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('Kotlin', 'Kotlin'), ('Python3', 'Python3')], max_length=20)),
                ('purpose', models.CharField(choices=[('기능구현', '기능구현'), ('리팩토링', '리팩토링')], max_length=5)),
                ('detail', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('userinput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userinput')),
            ],
        ),
    ]
