# Generated by Django 4.2.7 on 2023-11-23 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinput',
            old_name='languge',
            new_name='language',
        ),
    ]
